name: cmake

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check-up-to-date:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Check if all exercise cmake files are up to date
        run: ./bin/check-cmake-files-up-to-date
